DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(50) unique NOT NULL,
    password varchar(200) unique NOT NULL,
    birthday DATE
);

DROP TABLE IF EXISTS phones CASCADE;
CREATE TABLE IF NOT EXISTS phones (
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    phone varchar(25) unique NOT NULL
);

DROP TABLE IF EXISTS emails CASCADE;
CREATE TABLE IF NOT EXISTS emails (
    user_id BIGINT REFERENCES users(user_id) ON DELETE CASCADE,
    email varchar(50) unique NOT NULL
);

DROP TABLE IF EXISTS authorities CASCADE;
CREATE TABLE IF NOT EXISTS authorities (
    user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    authority varchar(20)
);

DROP TABLE IF EXISTS requests CASCADE;
CREATE TABLE IF NOT EXISTS requests (
    request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text varchar(1000),
    status varchar(100),
    created timestamp,
    processed timestamp,
    user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE
)